domains:
  - allowed_domains:
    - "angular.io"
    - "angular.dev"
    start_url: "https://angular.io/"
  - allowed_domains:
    - "api.drupal.org"
    start_url: "https://api.drupal.org/"
  - allowed_domains:
    - "api.haxe.org"
    start_url: "https://api.haxe.org/"
  - allowed_domains:
    - "api.qunitjs.com"
    start_url: "https://api.qunitjs.com/"
  - allowed_domains:
    - "babeljs.io"
    start_url: "https://babeljs.io/"
  - allowed_domains:
    - "backbonejs.org"
    start_url: "https://backbonejs.org/"
  - allowed_domains:
    - "bazel.build"
    start_url: "https://bazel.build/"
  - allowed_domains:
    - "bluebirdjs.com"
    start_url: "https://bluebirdjs.com/"
  - allowed_domains:
    - "bower.io"
    start_url: "https://bower.io/"
  - allowed_domains:
    - "cfdocs.org"
    start_url: "https://cfdocs.org/"
  - allowed_domains:
    - "clojure.org"
    start_url: "https://clojure.org/"
  - allowed_domains:
    - "clojuredocs.org"
    start_url: "https://clojuredocs.org/"
  - allowed_domains:
    - "codecept.io"
    start_url: "https://codecept.io/"
  - allowed_domains:
    - "codeception.com"
    start_url: "https://codeception.com/"
  - allowed_domains:
    - "codeigniter.com"
    start_url: "https://codeigniter.com/"
  - allowed_domains:
    - "coffeescript.org"
    start_url: "https://coffeescript.org/"
  - allowed_domains:
    - "cran.r-project.org"
    start_url: "https://cran.r-project.org/"
  - allowed_domains:
    - "crystal-lang.org"
    start_url: "https://crystal-lang.org/"
  - allowed_domains:
    - "forum.crystal-lang.org"
    start_url: "https://forum.crystal-lang.org/"
  - allowed_domains:
    - "css-tricks.com"
    start_url: "https://css-tricks.com/"
  - allowed_domains:
    - "dart.dev"
    start_url: "https://dart.dev/"
  - allowed_domains:
    - "dev.mysql.com"
    start_url: "https://dev.mysql.com/"
  - allowed_domains:
    - "developer.apple.com"
    start_url: "https://developer.apple.com/"
  - allowed_domains:
    - "developer.mozilla.org"
    start_url: "https://developer.mozilla.org/"
  - allowed_domains:
    - "developer.wordpress.org"
    start_url: "https://developer.wordpress.org/"
  - allowed_domains:
    - "doc.deno.land"
    start_url: "https://doc.deno.land/"
  - allowed_domains:
    - "doc.rust-lang.org"
    start_url: "https://doc.rust-lang.org/"
  - allowed_domains:
    - "docs.astro.build"
    start_url: "https://docs.astro.build/"
  - allowed_domains:
    - "docs.aws.amazon.com"
    start_url: "https://docs.aws.amazon.com/"
  - allowed_domains:
    - "docs.brew.sh"
    start_url: "https://docs.brew.sh/"
  - allowed_domains:
    - "docs.chef.io"
    start_url: "https://docs.chef.io/"
  - allowed_domains:
    - "docs.cypress.io"
    start_url: "https://docs.cypress.io/"
  - allowed_domains:
    - "docs.influxdata.com"
    start_url: "https://docs.influxdata.com/"
  - allowed_domains:
    - "docs.julialang.org"
    start_url: "https://docs.julialang.org/"
  - allowed_domains:
    - "docs.microsoft.com"
    start_url: "https://docs.microsoft.com/"
  - allowed_domains:
    - "docs.npmjs.com"
    start_url: "https://docs.npmjs.com/"
  - allowed_domains:
    - "docs.oracle.com"
    start_url: "https://docs.oracle.com/"
  - allowed_domains:
    - "docs.phalconphp.com"
    start_url: "https://docs.phalconphp.com/"
  - allowed_domains:
    - "docs.python.org"
    start_url: "https://docs.python.org/"
  - allowed_domains:
    - "docs.rs"
    start_url: "https://docs.rs/"
  - allowed_domains:
    - "docs.ruby-lang.org"
    start_url: "https://docs.ruby-lang.org/"
  - allowed_domains:
    - "docs.saltproject.io"
    start_url: "https://docs.saltproject.io/"
  - allowed_domains:
    - "docs.wagtail.org"
    start_url: "https://docs.wagtail.org/"
  - allowed_domains:
    - "doctrine-project.org"
    start_url: "https://doctrine-project.org/"
  - allowed_domains:
    - "docwiki.embarcadero.com"
    start_url: "https://docwiki.embarcadero.com/"
  - allowed_domains:
    - "eigen.tuxfamily.org"
    start_url: "https://eigen.tuxfamily.org/"
  - allowed_domains:
    - "elixir-lang.org"
    start_url: "https://elixir-lang.org/"
  - allowed_domains:
    - "elm-lang.org"
    start_url: "https://elm-lang.org/"
  - allowed_domains:
    - "enzymejs.github.io"
    start_url: "https://enzymejs.github.io/"
  - allowed_domains:
    - "erights.org"
    start_url: "https://erights.org/"
  - allowed_domains:
    - "erlang.org"
    start_url: "https://erlang.org/"
  - allowed_domains:
    - "esbuild.github.io"
    start_url: "https://esbuild.github.io/"
  - allowed_domains:
    - "eslint.org"
    start_url: "https://eslint.org/"
  - allowed_domains:
    - "expressjs.com"
    start_url: "https://expressjs.com/"
  - allowed_domains:
    - "fastapi.tiangolo.com"
    start_url: "https://fastapi.tiangolo.com/"
  - allowed_domains:
    - "flow.org"
    start_url: "https://flow.org/"
  - allowed_domains:
    - "fortran90.org"
    start_url: "https://fortran90.org/"
  - allowed_domains:
    - "fsharp.org"
    start_url: "https://fsharp.org/"
  - allowed_domains:
    - "getbootstrap.com"
    start_url: "https://getbootstrap.com/"
  - allowed_domains:
    - "getcomposer.org"
    start_url: "https://getcomposer.org/"
  - allowed_domains:
    - "git-scm.com"
    start_url: "https://git-scm.com/"
  - allowed_domains:
    - "gnu.org"
    start_url: "https://gnu.org/"
  - allowed_domains:
    - "gnucobol.sourceforge.io"
    start_url: "https://gnucobol.sourceforge.io/"
  - allowed_domains:
    - "go.dev"
    start_url: "https://go.dev/"
  - allowed_domains:
    - "golang.org"
    start_url: "https://golang.org/"
  - allowed_domains:
    - "graphite.readthedocs.io"
    start_url: "https://graphite.readthedocs.io/"
  - allowed_domains:
    - "groovy-lang.org"
    start_url: "https://groovy-lang.org/"
  - allowed_domains:
    - "gruntjs.com"
    start_url: "https://gruntjs.com/"
  - allowed_domains:
    - "handlebarsjs.com"
    start_url: "https://handlebarsjs.com/"
  - allowed_domains:
    - "haskell.org"
    start_url: "https://haskell.org/"
  - allowed_domains:
    - "hex.pm"
    start_url: "https://hex.pm/"
  - allowed_domains:
    - "hexdocs.pm"
    start_url: "https://hexdocs.pm/"
  - allowed_domains:
    - "httpd.apache.org"
    start_url: "https://httpd.apache.org/"
  - allowed_domains:
    - "i3wm.org"
    start_url: "https://i3wm.org/"
  - allowed_domains:
    - "jasmine.github.io"
    start_url: "https://jasmine.github.io/"
  - allowed_domains:
    - "javascript.info"
    start_url: "https://javascript.info/"
  - allowed_domains:
    - "jekyllrb.com"
    start_url: "https://jekyllrb.com/"
  - allowed_domains:
    - "jsdoc.app"
    start_url: "https://jsdoc.app/"
  - allowed_domains:
    - "julialang.org"
    start_url: "https://julialang.org/"
  - allowed_domains:
    - "knockoutjs.com"
    start_url: "https://knockoutjs.com/"
  - allowed_domains:
    - "kotlinlang.org"
    start_url: "https://kotlinlang.org/"
  - allowed_domains:
    - "laravel.com"
    start_url: "https://laravel.com/"
  - allowed_domains:
    - "latexref.xyz"
    start_url: "https://latexref.xyz/"
  - allowed_domains:
    - "lesscss.org"
    start_url: "https://lesscss.org/"
  - allowed_domains:
    - "love2d.org"
    start_url: "https://love2d.org/"
  - allowed_domains:
    - "lua.org"
    start_url: "https://lua.org/"
  - allowed_domains:
    - "man7.org"
    start_url: "https://man7.org/"
  - allowed_domains:
    - "mariadb.com"
    start_url: "https://mariadb.com/"
  - allowed_domains:
    - "mochajs.org"
    start_url: "https://mochajs.org/"
  - allowed_domains:
    - "modernizr.com"
    start_url: "https://modernizr.com/"
  - allowed_domains:
    - "momentjs.com"
    start_url: "https://momentjs.com/"
  - allowed_domains:
    - "mongoosejs.com"
    start_url: "https://mongoosejs.com/"
  - allowed_domains:
    - "next.router.vuejs.org"
    start_url: "https://next.router.vuejs.org/"
  - allowed_domains:
    - "next.vuex.vuejs.org"
    start_url: "https://next.vuex.vuejs.org/"
  - allowed_domains:
    - "nginx.org"
    start_url: "https://nginx.org/"
  - allowed_domains:
    - "nim-lang.org"
    start_url: "https://nim-lang.org/"
  - allowed_domains:
    - "nixos.org"
    start_url: "https://nixos.org/"
  - allowed_domains:
    - "nodejs.org"
    start_url: "https://nodejs.org/"
  - allowed_domains:
    - "npmjs.com"
    start_url: "https://npmjs.com/"
  - allowed_domains:
    - "ocaml.org"
    start_url: "https://ocaml.org/"
  - allowed_domains:
    - "odin-lang.org"
    start_url: "https://odin-lang.org/"
  - allowed_domains:
    - "openjdk.java.net"
    start_url: "https://openjdk.java.net/"
  - allowed_domains:
    - "opentsdb.net"
    start_url: "https://opentsdb.net/"
  - allowed_domains:
    - "perldoc.perl.org"
    start_url: "https://perldoc.perl.org/"
  - allowed_domains:
    - "php.net"
    start_url: "https://php.net/"
  - allowed_domains:
    - "playwright.dev"
    start_url: "https://playwright.dev/"
  - allowed_domains:
    - "pointclouds.org"
    start_url: "https://pointclouds.org/"
  - allowed_domains:
    - "postgresql.org"
    start_url: "https://postgresql.org/"
  - allowed_domains:
    - "prettier.io"
    start_url: "https://prettier.io/"
  - allowed_domains:
    - "pugjs.org"
    start_url: "https://pugjs.org/"
  - allowed_domains:
    - "pydata.org"
    start_url: "https://pydata.org/"
  - allowed_domains:
    - "pytorch.org"
    start_url: "https://pytorch.org/"
  - allowed_domains:
    - "qt.io"
    start_url: "https://qt.io/"
  - allowed_domains:
    - "r-project.org"
    start_url: "https://r-project.org/"
  - allowed_domains:
    - "react-bootstrap.github.io"
    start_url: "https://react-bootstrap.github.io/"
  - allowed_domains:
    - "reactivex.io"
    start_url: "https://reactivex.io/"
  - allowed_domains:
    - "reactjs.org"
    start_url: "https://reactjs.org/"
  - allowed_domains:
    - "reactnative.dev"
    start_url: "https://reactnative.dev/"
  - allowed_domains:
    - "reactrouterdotcom.fly.dev"
    start_url: "https://reactrouterdotcom.fly.dev/"
  - allowed_domains:
    - "readthedocs.io"
    start_url: "https://readthedocs.io/"
  - allowed_domains:
    - "readthedocs.org"
    start_url: "https://readthedocs.org/"
  - allowed_domains:
    - "redis.io"
    start_url: "https://redis.io/"
  - allowed_domains:
    - "redux.js.org"
    start_url: "https://redux.js.org/"
  - allowed_domains:
    - "requirejs.org"
    start_url: "https://requirejs.org/"
  - allowed_domains:
    - "rethinkdb.com"
    start_url: "https://rethinkdb.com/"
  - allowed_domains:
    - "ruby-doc.org"
    start_url: "https://ruby-doc.org/"
  - allowed_domains:
    - "ruby-lang.org"
    start_url: "https://ruby-lang.org/"
  - allowed_domains:
    - "rust-lang.org"
    start_url: "https://rust-lang.org/"
  - allowed_domains:
    - "rxjs.dev"
    start_url: "https://rxjs.dev/"
  - allowed_domains:
    - "sass-lang.com"
    start_url: "https://sass-lang.com/"
  - allowed_domains:
    - "scala-lang.org"
    start_url: "https://scala-lang.org/"
  - allowed_domains:
    - "scikit-image.org"
    start_url: "https://scikit-image.org/"
  - allowed_domains:
    - "scikit-learn.org"
    start_url: "https://scikit-learn.org/"
  - allowed_domains:
    - "spring.io"
    start_url: "https://spring.io/"
  - allowed_domains:
    - "sqlite.org"
    start_url: "https://sqlite.org/"
  - allowed_domains:
    - "stdlib.ponylang.io"
    start_url: "https://stdlib.ponylang.io/"
  - allowed_domains:
    - "superuser.com"
    start_url: "https://superuser.com/"
  - allowed_domains:
    - "svelte.dev"
    start_url: "https://svelte.dev/"
  - allowed_domains:
    - "swift.org"
    start_url: "https://swift.org/"
  - allowed_domains:
    - "tailwindcss.com"
    start_url: "https://tailwindcss.com/"
  - allowed_domains:
    - "twig.symfony.com"
    start_url: "https://twig.symfony.com/"
  - allowed_domains:
    - "typescriptlang.org"
    start_url: "https://typescriptlang.org/"
  - allowed_domains:
    - "underscorejs.org"
    start_url: "https://underscorejs.org/"
  - allowed_domains:
    - "vitejs.dev"
    start_url: "https://vitejs.dev/"
  - allowed_domains:
    - "vitest.dev"
    start_url: "https://vitest.dev/"
  - allowed_domains:
    - "vuejs.org"
    start_url: "https://vuejs.org/"
  - allowed_domains:
    - "vueuse.org"
    start_url: "https://vueuse.org/"
  - allowed_domains:
    - "webpack.js.org"
    start_url: "https://webpack.js.org/"
  - allowed_domains:
    - "wiki.archlinux.org"
    start_url: "https://wiki.archlinux.org/"
  - allowed_domains:
    - "www.chaijs.com"
    start_url: "https://www.chaijs.com/"
  - allowed_domains:
    - "www.electronjs.org"
    start_url: "https://www.electronjs.org/"
  - allowed_domains:
    - "www.gnu.org"
    start_url: "https://www.gnu.org/"
  - allowed_domains:
    - "www.hammerspoon.org"
    start_url: "https://www.hammerspoon.org/"
  - allowed_domains:
    - "www.khronos.org"
    start_url: "https://www.khronos.org/"
  - allowed_domains:
    - "www.lua.org"
    start_url: "https://www.lua.org/"
  - allowed_domains:
    - "www.php.net/manual/en/"
    start_url: "https://www.php.net/manual/en//"
  - allowed_domains:
    - "www.pygame.org"
    start_url: "https://www.pygame.org/"
  - allowed_domains:
    - "www.rubydoc.info"
    start_url: "https://www.rubydoc.info/"
  - allowed_domains:
    - "www.statsmodels.org"
    start_url: "https://www.statsmodels.org/"
  - allowed_domains:
    - "www.tcl.tk"
    start_url: "https://www.tcl.tk/"
  - allowed_domains:
    - "www.terraform.io"
    start_url: "https://www.terraform.io/"
  - allowed_domains:
    - "www.vagrantup.com"
    start_url: "https://www.vagrantup.com/"
  - allowed_domains:
    - "www.yiiframework.com"
    start_url: "https://www.yiiframework.com/"
  - allowed_domains:
    - "yarnpkg.com"
    start_url: "https://yarnpkg.com/"
  - allowed_domains:
    - "en.cppreference.com"
    start_url: "https://en.cppreference.com/"
  - allowed_domains:
    - "learn.microsoft.com"
    start_url: "https://learn.microsoft.com/"