# fly.toml app configuration file generated for mini-search-engine on 2025-01-15T22:25:35+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mini-search-engine'
primary_region = 'syd'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2

[mounts]
  source = "search_engine_data"
  destination = "/data"

[env]
  INDEX_PATH = "/data/index"
  DATABASE_PATH = "/data/crawler_output.db"

